version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: bash -c "sleep 5 && bundle exec rails server -b 0.0.0.0"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  db:
    image: postgres:latest
    ports:
      - "5432:5432" 
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:  
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
